config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/new'

  get 'comments/create'

  get 'transfers/index'

  get 'search_suggestions/user/:query', to: 'search_suggestions#user'

  get 'users/require_coinbase_account', as: :require_coinbase_account
  get 'users/link_coinbase_account', as: :link_coinbase_account
  get 'users/confirm_coinbase_account'
  get 'users/unlink_coinbase_account', as: :unlink_coinbase_account
  get 'users/access_qrcode', as: :access_qrcode
  get 'users/revoke_access_code', as: :revoke_access_code

  get 'sessions/destroy', as: :sign_out
  match 'sessions/authenticate', via: [:get, :post]
  get 'sessions/fail'
  get 'sessions/oauth', as: :oauth

  match '/dashboard', to: 'dashboard#dashboard', via: :get, as: :dashboard
  get 'dashboard/account_summary'
  get 'dashboard/transfer'
  get 'dashboard/buy_sell_bitcoin'
  get 'transfers/get_price'
  post 'transfers/create'
  get 'dashboard/access_qrcode_details'
  get 'dashboard/bitstation_feed'
  get 'dashboard/view_public_addresses'

  root :to => 'static_pages#homepage'

  match '/about', to: 'static_pages#about', via: :get, as: :about
  match '/beta', to: 'static_pages#beta', via: :get, as: :beta
  match '/security', to: 'static_pages#security', via: :get, as: :security
  match '/faq', to: 'static_pages#faq', via: :get, as: :faq
  match '/team', to: 'static_pages#team', via: :get, as: :team
  match '/privacy', to: 'static_pages#privacy', via: :get, as: :privacy

  resources :transactions, only: [:create, :index, :show] do
    resources :comments, only: [:index, :new, :create, :destroy] do
    end

    member do
      post 'annotate'
      get 'show_external'
    end
  end

  resources :transfers, only: [:create] do
  end

  resources :money_requests, path: 'requests', only: [:show, :index, :create] do
    member do
      post 'pay'
      post 'deny'
      post 'resend'
      post 'cancel'
    end
  end

  resources :contacts, only: [:create, :index, :show, :new, :destroy, :update] do
    collection do
      post 'import', as: :import
    end
  end

  resources :activities, only: [:index] do
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :ensure_signed_in, only: [:dashboard, :overview]
  before_filter :ensure_signed_in_without_redirect, only: [:account_summary, :transfer, :transaction_history, :transaction_details, :buy_sell_bitcoin, :access_qrcode_details]
  before_filter :check_for_unlinked_coinbase_account, only: [:transfer, :address_book, :transaction_details, :buy_sell_bitcoin]

  def dashboard
    store_location
    @subtitle = "Dashboard"
    @popup = params[:popup]
  end

  def transfer
    @is_module = true
    @default_currency = 'USD'
    @exchange_rate = current_coinbase_client.spot_price("USD").to_d

    render layout: false
  end

  def account_summary
    @is_module = true
    if has_coinbase_account_linked?
      @current_balance = current_coinbase_client.balance.to_d
      @current_balance_usd = current_coinbase_client.spot_price("USD").to_d * @current_balance
    end

    render layout: false
  end

  def access_qrcode_details
    @qr_path = access_qrcode_path(current_user, r: Time.now.to_f.to_s)
    render layout: false
  end

  def view_public_addresses
    @public_address = current_coinbase_client.get('/addresses').to_hash
    @public_address = @public_address["addresses"]
    render layout: false
  end

  def buy_sell_bitcoin
    @is_module = true
    @current_sell_price = current_coinbase_client.get('/prices/sell', {"qty"=>"1"})["subtotal"]["amount"]
    @current_buy_price = current_coinbase_client.get('/prices/buy', {"qty"=>"1"})["subtotal"]["amount"]
    render layout: false
  end

  def bitstation_feed
    @is_module = true
    render layout: false
  end

  private

    def check_for_unlinked_coinbase_account
      render 'unlinked_coinbase_account', layout: false unless has_coinbase_account_linked?
    end

    def disable_module
      render inline: ''
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_module.html.erb
<section class="module panel panel-default <%= expandable ? 'expandable' : '' %> col-lg-4 col-sm-6 col-xs-12">
  <h5 class="panel-heading"><%= title %></h5>
  <div data-load="<%= content_path %>" id="<%= name %>_module" data-load-order="<%= load_order %>">
    <%= render 'spinner' %>
  </div>
</section>

app/views/dashboard/_spinner.html.erb
<div>
  <div class="dashboard-module-spinner-container">
    <i class="fa fa-circle-o-notch fa-spin fa-2x"></i>
  </div>
</div>

app/views/dashboard/access_qrcode_details.html.erb
<div><%= image_tag @qr_path, id: 'access_qrcode' %></div>

app/views/dashboard/account_summary.html.erb
<% if has_coinbase_account_linked? %>
<div class="panel-body">
	<label>Balance</label>
	<div id="balances">
		<span class="well well-sm"><%= friendly_amount(@current_balance, "BTC", {:round => 4})[0..-4] %><i class="fa fa-btc"></i></span>
		<br><br><span class="well well-sm"><%= friendly_amount(@current_balance_usd, "USD", {:round => 4}) %></span>
	</div>
</div>
<hr>
<% end %>
<div class="panel-body">
	<label>Coinbase</label>
  <% if has_coinbase_account_linked? %>
		<p>Currently linked account: <span class="label label-default"><%= current_user.coinbase_account.email %></span></p>
    <p class="text-center">
      <%= link_to 'Unlink this account', unlink_coinbase_account_path, class: "btn btn-primary", data: {confirm: 'Do you really want to unlink your Coinbase account? '} %>
      <%= link_to 'Import Contacts', import_contacts_path, method: :post, class: 'btn btn-primary' %>
	  <%= link_to 'View Public BitCoin Addresses', dashboard_view_public_addresses_path,class: "btn btn-primary popuppable", 'data-load' => "#{dashboard_view_public_addresses_path}" %>

    </p>
  <% else %>
    <p>You haven't linked a Coinbase account yet.</p>
    <p class="text-center"><%= link_to 'Link a Coinbase account', link_coinbase_account_path,  class: "btn btn-primary" %></p>
  <% end %>
</div>
<% unless signed_in_with_access_code? %>
<hr>
<div class="panel-body">
	<label>Access BitStation from your phone</label>
	<p class="text-center">
	  <%= link_to 'Get QR Access Code', :access_qrcode, class: "btn btn-primary popuppable", 'data-load' => "#{dashboard_access_qrcode_details_path}" %>
	  <%= link_to 'Revoke QR Code', :revoke_access_code, class: "btn btn-primary" %>
  </p>
</div>

<% end %>

app/views/dashboard/bitstation_feed.html.erb
<div class="panel-body">
	<div class="media">
	  <a class="pull-left" href="http://bit.ly/hungrymitch2">
	    <img class="media-object" src="http://bit.ly/hungrymitch2" alt="Hungry Mitch">
	  </a>
	  <div class="media-body">
	    <h5 class="media-heading">Mitchell Gu sent Eric Lander 24 BTC!</h5>
	    <p>Thanks for all the bio lectures!</p>
			<button type="button" class="btn btn-primary btn-xs"><i class="fa fa-thumbs-o-up"></i> Like</button>
	  </div>
	</div>
</div>

app/views/dashboard/buy_sell_bitcoin.html.erb
<%= form_tag transfers_create_path, id: 'buy_sell_form' %>
<div class="panel-body">
  <div class="form-group">
    <div class="btn-group btn-group-justified" id="buy_sell_action_btn_group">
      <a class="btn btn-default btn-primary">Buy</a>
      <a class="btn btn-default">Sell</a>
    </div>
    <%= hidden_field_tag 'transfer_action', 'buy' %>
  </div>

<div id="sellprice" style="display: none;">
  <label>Current Sell Price:</label><p><span class="well well-sm"> 1 BTC = <span id='sell_current_rate'><%= @current_sell_price %></span> USD</span> (not including fees)</p>
</div>

<div id="buyprice">
  <label>Current Buy Price:</label><p><span class="well well-sm"> 1 BTC = <span id='buy_current_rate'><%= @current_buy_price %></span> USD</span> (not including fees)</p>
</div>

  <div class="form-group">
    <%= label_tag 'amount' %>
    <div class="input-group">
      <%= text_field_tag 'amount', '', placeholder: 'BTC amount', class: 'form-control', onkeypress: 'window.validateNumField(event)' %>
      <span class="input-group-addon">BTC <i class="fa fa-exchange"></i> USD</span>
      <%= text_field_tag 'preview_amount', '', placeholder: 'USD amount', class: 'form-control', onkeypress: 'window.validateNumField(event)' %>
    </div><!-- /input-group -->
  </div>

  <table class="table buy-sell-table">
    <tbody>
      <tr>
        <td>Subtotal</td>
        <td id="table-amount-subtotal" class="table-amount">0.00 USD</td>
      </tr>
      <tr>
        <td>Coinbase Fees</td>
        <td id="table-amount-coinbase"  class="table-amount">0.00 USD</td>
      </tr>
      <tr>
        <td>Bank Fees</td>
        <td id="table-amount-bank"  class="table-amount">0.00 USD</td>
      </tr>
      <tr class="table-total">
        <td>Total</td>
        <td id="table-amount-total"  class="table-amount">0.00 USD</td>
      </tr>
    </tbody>
  </table>

  <%= submit_tag 'Confirm', class: 'btn btn-primary' %>
</div>

</form>

app/views/dashboard/contact_details.html.erb
<div>Contact Details</div>

app/views/dashboard/exchange_currencies.html.erb
<div class="panel-body">
  <%= form_tag request_bitcoin_path, id: 'exchange_bitcoin_form' %>
  <div class="form-group">
    <%= label_tag 'amount' %>
    <div class="input-group">
      <%= text_field_tag 'amount', '', placeholder: 'The amount of USD', class: 'form-control' %>
      <div class="btn-group input-group-btn">
        <button type="button" class="btn btn-default dropdown-toggle form-control" data-toggle="dropdown">
          <span data-bind="label" id="sendlabel">USD</span> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">USD</a></li>
          <li><a href="#">BTC</a></li>
        </ul>
        <input type="hidden" name="currency" value="USD">
      </div><!-- /btn-group -->
    </div><!-- /input-group -->
  </div>
</div>
<hr>

<div class="panel-body">
  <label>Current BitCoin Sell Price</label>
  <div id="balances">
    <br><span class="well well-sm"> 1 BTC = <%= @current_sell_price %></span>
  </div>
</div>
<br>
<hr>

<div class="panel-body">
  <%= submit_tag 'Authorize Transaction', class: 'btn btn-default' %>
</div>

</form>

<script>
    // FIXME This is ugly...
    // window.setup_recipient_autocomplete();
    </script>
  </div>

app/views/dashboard/transaction_details.html.erb
<div class="panel-body transaction_details">
	<h4>Transaction <%= @transaction_id %></h4>
	<p><%= DateTime.parse(@transaction_date).strftime('%b %d, %Y at %I:%M %p') %></p>
	<p><span class="label label-<%= @transaction['amount'] > 0 ? 'success' : 'danger' %>"><%= friendly_amount_from_money(@transaction['amount'], {:round=>4}) %></span>
		<% if @transaction['amount'] < 0 %>
			<%= '<span class="label label-danger">Outgoing</span>'.html_safe %>
		<% elsif @transaction['amount'] > 0 %>
			<%= '<span class="label label-success">Incoming</span>'.html_safe %>
		<% end %>
		<% if @transaction['status'] == "pending" %>
			<%= '<span class="label label-warning">Pending</span>'.html_safe %>
		<% elsif @transaction['status'] == "complete" %>
			<%= '<span class="label label-success">Complete</span>'.html_safe %>
		<% end %>
	</p>
</div>
<hr>
<div class="panel-body transaction_details">
	<h4>Sender</h4>
	<p>Name: <%= @transaction_sender_name %></p>
	<p>Coinbase email: <%= @transaction_sender_email %></p>
</div>
<hr>
<div class="panel-body transaction_details">
	<h4>Recipient</h4>
	<p>Name: <%= @transaction_recipient_name %></p>
	<p>Coinbase email: <%= @transaction_recipient_email %></p>
</div>
<hr>
<div class="panel-body transaction_details">
	<p><%= @footer.html_safe %><p>
</div>

app/views/dashboard/transaction_history.html.erb
<% unless @current_page == 1 %>
  <%= link_to dashboard_transaction_history_path(page: @current_page - 1), remote: true do %>
    <i class="fa fa-lg fa-chevron-circle-left paging paging-left"></i>
  <% end %>
<% end %>

<% if @might_have_next_page %>
  <%= link_to dashboard_transaction_history_path(page: @current_page + 1), remote: true do %>
    <i class="fa fa-lg fa-chevron-circle-right paging paging-right"></i>
  <% end %>
<% end %>
<% if @history.empty? %>
  <div class="panel-body">
    <p>No more transaction history to show.</p>
  </div>
<% end %>
<table class="transaction-history-table table table-striped table-responsive table-hover table-condensed">
  <tbody>
    <% @history.each do |entry| %>
      <!-- TODO ignore request transactions for now -->
      <% next if entry['request'] %>
      <!-- TODO put data-load attr in tr for popup card ajax load -->
      <tr class="popuppable" data-load="<%= dashboard_transaction_details_path(id: entry['id']) %>" >
        <td class="fit-to-contents first-column"><%= (DateTime.parse(entry['created_at']).to_date == @previous_date.to_date rescue false) ? '' : DateTime.parse(entry['created_at']).strftime('%b %d') %></td>
        <td class="fit-to-contents"><span class="label label-<%= entry['sender']['id'] == @coinbase_id ? 'danger' : 'success' %> amount"><%= friendly_amount_from_money(entry['amount']) %></span></td>
        <td class="fit-to-contents">
          <% if entry['transfer_type'] %>
            <%= entry['transfer_type'] %>
          <% else %>
            <%= entry['sender']['id'] == @coinbase_id ? '<i class="fa fa-long-arrow-right"></i>'.html_safe : '<i class="fa fa-long-arrow-left"></i>'.html_safe%></td>
          <% end %>
        <td class="ellipsis">
          <div class="td-truncate">
              <% unless entry['transfer_type'] %>
                <% if entry['sender']['id'] == @coinbase_id %>
                  <%= entry['recipient'] ? (CoinbaseAccount.find_by_email(entry['recipient']['email']).user.name rescue entry['recipient']['name']) : 'External Account' %>
                <% else %>
                  <%= entry['sender'] ? (CoinbaseAccount.find_by_email(entry['sender']['email']).user.name rescue entry['sender']['name']) : 'External Account' %>
                <% end %>
              <% end %>
          </div>
        </td>
        <td class="fit-to-contents last-column">
          <% unless entry['transfer_type'] %>
            <% if entry['sender']['id'] == @coinbase_id %>
              <%= entry['recipient'] ? (CoinbaseAccount.find_by_email(entry['recipient']['email']).nil? ? '<span title="This person is a Coinbase user" class="label label-info">C</span>'.html_safe : '<span title="This person is a MIT user" class="label label-danger">M</span>'.html_safe) : '<span title="This person is an external user" class="label label-success">E</span>'.html_safe %>
            <% else %>
              <%= entry['sender'] ? (CoinbaseAccount.find_by_email(entry['sender']['email']).nil? ? '<span title="This person is a Coinbase user" class="label label-info">C</span>'.html_safe : '<span title="This person is a MIT user" class="label label-danger">M</span>'.html_safe) : '<span title="This person is an external user" class="label label-success">E</span>'.html_safe %>
            <% end %>
          <% end %>
          <% if entry['status'] == 'pending' %>
            <span title="This transaction is pending" class="label label-warning">P</span>
          <% end %>
        </td>
      </tr>
      <% @previous_date = DateTime.parse(entry['created_at']) %>
    <% end %>
  </tbody>
</table>

<!-- FIXME this too is ugly -->
<script>
  window.setup_transaction_history_paging_links();
</script>

app/views/dashboard/transaction_history_detailed.html.erb
<div>Test 2</div>

app/views/dashboard/transfer.html.erb
<div>
  <%= form_tag transactions_path, id: 'transfer_form', 'data-send-path' => transactions_path, 'data-request-path' => money_requests_path %>
    <%= hidden_field_tag 'exchange_rate', @exchange_rate %>
    <%= hidden_field_tag 'fee_amount', (@send_money[:fee_amount] rescue 0) %>
    <div class="form-group">
      <%= label_tag 'action' %>
      <div class="btn-group btn-group-justified" id="transfer_action_btn_group">
        <a class="btn btn-default btn-primary">Send</a>
        <a class="btn btn-default">Request</a>
      </div>
      <%= hidden_field_tag 'action', 'send' %>
    </div>

    <div class="form-group">
      <%= label_tag 'Recipient' %>
      <%= text_field_tag 'kerberos', (@send_money[:recipient] rescue nil), placeholder: 'Kerberos ID or BTC Address', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag 'amount' %>
      <div class="input-group">
        <div class="input-group">
          <%= text_field_tag 'amount_usd', '', placeholder: 'USD amount', class: 'form-control' %>
          <span class="input-group-addon">USD = BTC</span>
          <%= text_field_tag 'amount_btc', '', placeholder: 'BTC amount', class: 'form-control' %>
        </div><!-- /input-group -->
      </div><!-- /input-group -->
    </div>

    <div class="form-group">
      <%= label_tag 'Message' %>
      <div class="input-group">
        <%= text_field_tag 'message', '', placeholder: 'A kind word or two', class: 'form-control' %>
        <%= hidden_field_tag 'is_public', false %>
        <div class="input-group-btn">
          <button id="toggle_publicity_button" class="btn btn-default">Private</button>
        </div>
      </div>
      <p class="field-explanation pull-right">Click here to make the transaction public <i class="fa fa-arrow-up"></i></p>
    </div>

    <%= submit_tag 'Send Money', class: 'btn btn-primary' %>
  </form>

  <script>
    // FIXME This is ugly...
    window.setup_recipient_autocomplete("transfer_form");
    window.setup_transfer_button();
  </script>
</div>

app/views/dashboard/unlinked_coinbase_account.html.erb
<div class="panel-body">
  <p>Click <%= link_to 'here', link_coinbase_account_path %> to link a Coinbase account first. </p>
</div>

app/views/dashboard/view_public_addresses.html.erb
<div class="panel-body transaction_details">
	<div class="panel-body transaction_details">
		<h4>Your Public Bitcoin Addresses:</h4>
		(click to view info on the blockchain)
		<% @public_address.each do |key| %>
			<% @useraddress = key["address"]["address"] %>
			<% @url = "https://blockchain.info/address/" + @useraddress %>
			<p><%= link_to @useraddress, @url %></p>
		<% end %>
	</div>
</div>