config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/new'

  get 'comments/create'

  get 'transfers/index'

  get 'search_suggestions/user/:query', to: 'search_suggestions#user'

  get 'users/require_coinbase_account', as: :require_coinbase_account
  get 'users/link_coinbase_account', as: :link_coinbase_account
  get 'users/confirm_coinbase_account'
  get 'users/unlink_coinbase_account', as: :unlink_coinbase_account
  get 'users/access_qrcode', as: :access_qrcode
  get 'users/revoke_access_code', as: :revoke_access_code

  get 'sessions/destroy', as: :sign_out
  match 'sessions/authenticate', via: [:get, :post]
  get 'sessions/fail'
  get 'sessions/oauth', as: :oauth

  match '/dashboard', to: 'dashboard#dashboard', via: :get, as: :dashboard
  get 'dashboard/account_summary'
  get 'dashboard/transfer'
  get 'dashboard/buy_sell_bitcoin'
  get 'transfers/get_price'
  post 'transfers/create'
  get 'dashboard/access_qrcode_details'
  get 'dashboard/bitstation_feed'
  get 'dashboard/view_public_addresses'

  root :to => 'static_pages#homepage'

  match '/about', to: 'static_pages#about', via: :get, as: :about
  match '/beta', to: 'static_pages#beta', via: :get, as: :beta
  match '/security', to: 'static_pages#security', via: :get, as: :security
  match '/faq', to: 'static_pages#faq', via: :get, as: :faq
  match '/team', to: 'static_pages#team', via: :get, as: :team
  match '/privacy', to: 'static_pages#privacy', via: :get, as: :privacy

  resources :transactions, only: [:create, :index, :show] do
    resources :comments, only: [:index, :new, :create, :destroy] do
    end

    member do
      post 'annotate'
      get 'show_external'
    end
  end

  resources :transfers, only: [:create] do
  end

  resources :money_requests, path: 'requests', only: [:show, :index, :create] do
    member do
      post 'pay'
      post 'deny'
      post 'resend'
      post 'cancel'
    end
  end

  resources :contacts, only: [:create, :index, :show, :new, :destroy, :update] do
    collection do
      post 'import', as: :import
    end
  end

  resources :activities, only: [:index] do
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :ensure_signed_in, only: []
  before_filter :ensure_coinbase_account_linked, only: [:create]
  before_filter :check_for_unlinked_coinbase_account, only: [:index, :show]
  before_filter :ensure_signed_in_without_redirect, only: [:annotate]

  include ApplicationHelper

  CURRENCIES = ["USD", "BTC"]

  MINIMUM_TRANSACTION_AMOUNT = {
    "BTC" => 0.001,
    "USD" => 0.5
  }

  TRANSACTION_HISTORY_ENTRIES_PER_PAGE = 11
  DETAILED_TRANSACTION_HISTORY_ENTRIES_PER_PAGE = 100

  class TransactionParameterError < StandardError; end

  def create
    recipient = params[:kerberos]
    amount = params[:amount_btc].to_f
    fee_amount = params[:fee_amount].to_f rescue 0
    message = params[:message] || ''
    currency = 'BTC'
    is_public = params[:is_public].to_bool rescue false
    pt = nil

    @error = nil

    recipient_type = User.address_type(recipient)

    user = User.find_by(kerberos: recipient) if (recipient_type == :bitstation)

    begin
      (@error = 'Invalid currency. ' and raise TransactionParameterError) unless CURRENCIES.include?(currency)
      (@error = 'Invalid address. ' and raise TransactionParameterError) if recipient_type.nil?
      (@error = 'Why sending yourself money...? ' and raise TransactionParameterError) if user && (user == current_user)
      (@error = "Invalid transfer amount. The minimum transaction amount is #{MINIMUM_TRANSACTION_AMOUNT[currency]} #{currency}." and raise TransactionParameterError) if amount.nil? || amount < MINIMUM_TRANSACTION_AMOUNT[currency]

      spot_price = current_coinbase_client.spot_price('USD').to_d
      dollar_amount = amount * spot_price
      (@error = "You do not have enough funds in your Coinbase account. " and raise TransactionParameterError) if amount > current_coinbase_client.balance.to_d

      if (recipient_type == :bitstation) && user.nil?
        @warning = "The recipient hasn't joined BitStation yet. We have sent an invitation to him / her at #{recipient}@mit.edu. "
        TransactionMailer.invite_recipient(current_user, recipient, amount, dollar_amount, root_url).deliver
      elsif (recipient_type == :bitstation) && user.coinbase_account.nil?
        @warning = "The recipient hasn't linked a Coinbase account yet. We have sent an notification to him / her at #{recipient}@mit.edu. "
        TransactionMailer.remind_link_coinbase_account(current_user, recipient, amount, dollar_amount, link_coinbase_account_url).deliver
      else
        pt = (recipient_type == :bitstation) ?
          Transaction.create!({sender: current_user, recipient: user, amount: amount, message: message, fee_amount: fee_amount, is_public: is_public}) :
          Transaction.create!({sender: current_user, recipient: nil, recipient_address: recipient, amount: amount, message: message, fee_amount: fee_amount, is_public: is_public})
      end
    rescue TransactionParameterError
    end

    respond_to do |format|
      format.html do
        if @error
          redirect_to dashboard_url, flash: {error: @error}
        elsif @warning
          redirect_to dashboard_url, flash: {warning: @warning}
        else
          # FIXME ugh
          redirect_to @oauth_client.auth_code.authorize_url(redirect_uri: coinbase_callback_uri + '?pending_action=transact&pending_action_id=' + pt.id.to_s) + '&scope=send+user'
        end
      end
    end
  end

  def index
    @is_module = true
    client = current_coinbase_client
    page = params[:page] || 1
    page = page.to_i
    current_page = page
    entries_per_page = params[:detailed] ? DETAILED_TRANSACTION_HISTORY_ENTRIES_PER_PAGE : TRANSACTION_HISTORY_ENTRIES_PER_PAGE

    cb_response = client.transactions(page, limit: entries_per_page)
    coinbase_id = cb_response['current_user']['id']
    num_pages = cb_response['num_pages'].to_i
    # FIXME assuming the user has no more than 1000 transfers
    transfers = client.transfers(limit: [1000, page * entries_per_page].min)
    transfers = transfers['transfers'].map { |t| t['transfer'] }
    cb_transactions = cb_response['transactions'].map { |t| t['transaction'] }

    cb_transactions.each do |e|
      ts = transfers.select { |t| t['transaction_id'] == e['id'] }
      e['transfer_type'] = ts.first['type'].downcase unless ts.empty?
    end

    @display = cb_transactions.map do |t|
      # TODO ignore request transactions for now
      next if t['request']
      Transaction.display_data_from_cb_transaction(t, coinbase_id, current_user)
    end

    @next_page = (current_page < num_pages) ? transactions_path(page: current_page + 1) : nil
    @prev_page = (current_page != 1) ? transactions_path(page: current_page - 1) : nil

    if params[:detailed]
      render "index_detailed", layout:false
    else
      respond_to do |format|
        format.js do
          @rendered_html = render_to_string(formats: [:html]).lines.join('').html_safe
          # raise @rendered_html.lines.count.to_s
          render formats: [:js]
        end

        format.html do
          render layout: false
        end
      end
    end
  end


  def show
    @transaction_id = params['id']
    @is_coinbase = is_coinbase_transaction_id?(@transaction_id)

    if @is_coinbase
      client = current_coinbase_client

      @transaction = client.transaction(@transaction_id)['transaction']

      @transaction_date = Time.parse(@transaction['created_at']).localtime.to_s[0..-7]

      if @transaction['hsh'].nil?
        @footer = "This transaction occurred within the Coinbase network and off the blockchain with zero fees."
      else
        @footer = '<a target=“_blank” href="https://coinbase.com/network/transactions/' + @transaction['hsh'] + '">View this transaction on the blockchain</a>'
      end

      if @transaction[:sender].nil?
        @transaction_sender_name = "External BTC Address"
        @transaction_sender_email = @transaction[:sender_address]
      else
        @transaction_sender_name = @transaction[:sender][:name]
        @transaction_sender_email = @transaction[:sender][:email]
      end
      if @transaction[:recipient].nil?
        if @transaction[:sender][:email] == current_user.coinbase_account.email
          @transaction_recipient_name = "External BTC Address"
          @transaction_recipient_email = @transaction[:recipient_address]
        else
          @transaction_recipient_name = current_user.name
          @transaction_recipient_email = "Sent to your receiving BTC Address"
        end
      else
        @transaction_recipient_name = @transaction[:recipient][:name]
        @transaction_recipient_email = @transaction[:recipient][:email]
      end

      # TODO: Get full names from our user database if possible, not coinbase
      @transaction_json = @transaction.to_json
      @display_data = Transaction.display_data_from_cb_transaction(@transaction, nil, current_user)
    else
      @transaction = Transaction.find(@transaction_id)
      @a = @transaction.to_activity

      @from = @transaction.sender == current_user ?
        'You' :
        @transaction.sender.name
      @to = @transaction.recipient.nil? ?
        'External User' :
        (
          @transaction.recipient == current_user ?
          'you' :
          @transaction.recipient.name
        )
    end

    render layout: false
  end

  def show_external
    @transaction_id = params['id']
    @is_coinbase = is_coinbase_transaction_id?(@transaction_id)
    @transaction = Transaction.find(@transaction_id)
    @a = @transaction.to_activity

    @from = @transaction.sender == current_user ?
      'You' :
      @transaction.sender.name
    @to = @transaction.recipient.nil? ?
      'External User' :
      (
        @transaction.recipient == current_user ?
        'you' :
        @transaction.recipient.name
      )
  end

  def annotate
    @id = params[:id]
    @content = params[:content]
    note = Note.find_or_create_by(
      user_id: current_user.id,
      coinbase_transaction_id: @id
    )

    note.update!(content: @content)
  end

  private

    COINBASE_TRANSACTION_ID_REGEX = /[0-9a-zA-Z]{24}/

    def is_coinbase_transaction_id?(id)
      id =~ COINBASE_TRANSACTION_ID_REGEX
    end
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/transactions/annotate.js.erb
$('#annotate_transaction_' + "<%= @id %>").update_edit_field('content', "<%=j @content.html_safe %>");
$('#annotate_transaction_' + "<%= @id %>").end_edit();
$('#annotate_transaction_' + "<%= @id %>").closest('td').find('>div').removeClass('unpadded');

app/views/transactions/index.html.erb
<%= render 'account_activity_history', id: 'transaction-history-table', data: @display, activity: 'transaction', prev_page: @prev_page, next_page: @next_page %>

<!-- FIXME this too is ugly -->
<script>
  window.setup_paging_links('#transaction-history-table');
</script>

app/views/transactions/index.js.erb
$('#account_activity_history_module').html('<%= j @rendered_html %>')

app/views/transactions/index_detailed.html.erb
<table id="transaction-history-table-detailed" class="table table-striped table-responsive table-hover table-condensed">
  <tbody>
    <tr>
      <th>
        <div id="cleardate"style="">
          <input class="form-control" id="filter-date" placeholder="Date" type="text">
            <span class="fa-stack fa-lg" id="clearfilterspan">
              <i class="fa fa-times-circle" id="clearfilter"></i>
            </span>
       </div>
      </th>

      <th><input class="form-control" id="filter-amount" placeholder="Amount" type="text"></th>
      <th></th>
      <th><input class="form-control" id="filter-name" placeholder="Filter by Contact Name" type="text"></th>
      <th><input class="form-control" id="filter-note" placeholder="Filter by Note" type="text"></th>
      <th></th>
    </tr>
    <% @display.each_with_index do |e, i| %>
      <tr class="popuppable" data-load="<%= e[:load] %>" >
        <td class="fit-to-contents first-column transaction-detailed-date"><div>
            <%= e[:display_time] %>
        </div></td>

        <td class="fit-to-contents transaction-detailed-amount"><div>
          <span class="label label-<%= (e[:money_direction] || e[:direction]) == :to ? 'danger' : 'success' %> amount"><%= e[:amount] %></span>
        </div></td>

        <td class="fit-to-contents"><div>
            <%= e[:direction] == :to ? '<i class="fa fa-long-arrow-right"></i>'.html_safe : '<i class="fa fa-long-arrow-left"></i>'.html_safe %>
        </div></td>

        <td class="ellipsis transaction-detailed-name"><div>
          <div class="td-truncate">
          <%= e[:target] %>
          </div>
        </div></td>

        <td class="ellipsis transaction-detailed-note"><div>
          <div class="td-truncate">
            <%= form_tag e[:note][:edit_path], id: e[:note][:form_id], remote: true %>
              <% note = e[:note][:content] rescue nil %>
              <%= text_field_tag :content, note, class: 'form-control', data: {display_role: 'edit', display_field: 'content'}, placeholder: "Press enter to confirm" %>
              <p data-display-role="display" data-display-field="content">
                <% if note && !note.empty? %>
                  <%= note %>
                <% else %>
                  No note assigned.
                <% end %>
              </p>
            </form>
          </div>
        </div></td>

        <td class="fit-to-contents last-column"><div>
          <% if e[:transfer_type] %>
            <% if e[:transfer_type] == "sell" %>
              <span class="label label-danger address-type-label-char ">S</span>
            <% else %>
              <span class="label label-success address-type-label-char ">B</span>
            <% end %>
          <% else %>
            <%= address_type_label(e[:target_type], :char) %>
          <% end %>

          <% if e[:pending] %>
            <span title="This transaction is pending" class="label label-warning">P</span>
          <% end %>

          <% if e[:success] %>
            <span title="This transaction is <%= e[:success] %>" class="label label-success"><%= e[:success][0].upcase %></span>
          <% end %>

          <% if e[:failure] %>
            <span title="This transaction is <%= e[:failure] %>" class="label label-danger"><%= e[:failure][0].upcase %></span>
          <% end %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  window.recalculate_truncate_width("#transaction-history-table-detailed");
  $("#filter-name, #filter-date, #filter-amount, #filter-message, #filter-note").change(function() {
    $("#transaction-history-table-detailed").filterTable([[".transaction-detailed-date", $("#filter-date").val()], [".transaction-detailed-amount", $("#filter-amount").val()], [".transaction-detailed-name", $("#filter-name").val()], [".transaction-detailed-message", $("#filter-message").val()], [".transaction-detailed-note", $("#filter-note").val()]]);
  }).keyup(function() {
    return $(this).change();
  });
  $("#filter-date").datepicker({
    format: "M dd",
    autoclose: true,
    todayHighlight: true
  });
</script>

app/views/transactions/request_money.js.erb
window.trigger_popup_alert("<%= j @success || @error %>", "<%= @success ? 'success': 'error' %>");

app/views/transactions/show.html.erb
<% if @is_coinbase %>
	<div class="panel-body transaction_details">
		<h4>Transaction <%= @transaction_id %></h4>

		<p><%= DateTime.parse(@transaction_date).strftime('%b %d, %Y at %I:%M %p') %></p>

		<% note = @display_data[:note][:content] rescue nil %>
		<% if note && !note.empty? %>
			<p><%= @display_data[:note][:content] %></p>
		<% end %>

		<p><span class="label label-<%= @transaction['amount'] > 0 ? 'success' : 'danger' %>"><%= friendly_amount_from_money(@transaction['amount'], {:round=>4}) %></span>
			<% if @transaction['amount'] < 0 %>
				<%= '<span class="label label-danger">Outgoing</span>'.html_safe %>
			<% elsif @transaction['amount'] > 0 %>
				<%= '<span class="label label-success">Incoming</span>'.html_safe %>
			<% end %>
			<% if @transaction['status'] == "pending" %>
				<%= '<span class="label label-warning">Pending</span>'.html_safe %>
			<% elsif @transaction['status'] == "complete" %>
				<%= '<span class="label label-success">Complete</span>'.html_safe %>
			<% end %>
		</p>
	</div>
	<hr>
	<div class="panel-body transaction_details">
		<h4>Sender</h4>
		<p><%= @transaction_sender_name %></p>
		<p><%= @transaction_sender_email %></p>
	</div>
	<hr>
	<div class="panel-body transaction_details">
		<h4>Recipient</h4>
		<p><%= @transaction_recipient_name %></p>
		<p><%= @transaction_recipient_email %></p>
	</div>
	<hr>
	<div class="panel-body transaction_details">
		<p><%= @footer.html_safe %><p>
	</div>
<% else %>
	<div class="panel-body">
		<h4>Transaction Details</h4>
		<p>Made on <%= @transaction.created_at.strftime('%b %d, %Y at %I:%M %p') %></p>

		<%= transaction_description_labels(@from, :send, @to, @transaction.amount) %>
    <p><div class="fb-like" data-href="<%= @a[:like_link] %>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div></p>
	</div>

	<hr>

	<div>
		<div data-load="<%= new_transaction_comment_path(@transaction) %>" data-load-order="1"></div>

		<div data-load="<%= transaction_comments_path(@transaction) %>" data-load-order="2">
			Loading comments...
		</div>
	</div>

	<%= javascript_tag do -%>
		window.load_contents();
	<% end %>
<% end %>

app/views/transactions/show_external.html.erb
<section  id="popup-card-wrapper" class="module panel panel-default transition col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3 col-xs-12 col-xs-offset-0">
  <h5 class="panel-heading">BitStation Public Transaction</h5>
  <div>
		<div class="panel-body">
			<h4>Transaction Details</h4>
			<p>Made on <%= @transaction.created_at.strftime('%b %d, %Y at %I:%M %p') %></p>

			<%= transaction_description_labels(@from, :send, @to, @transaction.amount) %>
      <p><div class="fb-like" data-href="<%= @a[:like_link] %>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div></p>
		</div>

		<hr>

		<div>
			<div data-load="<%= new_transaction_comment_path(@transaction) %>" data-load-order="1"></div>

			<div data-load="<%= transaction_comments_path(@transaction) %>" data-load-order="2">
				Loading comments...
			</div>
		</div>

		<%= javascript_tag do -%>
			window.load_contents();
		<% end %>
  </div>
</section>
<div id="mask" class="transition"></div>
<div id="mask2" class="transition"></div>