config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/new'

  get 'comments/create'

  get 'transfers/index'

  get 'search_suggestions/user/:query', to: 'search_suggestions#user'

  get 'users/require_coinbase_account', as: :require_coinbase_account
  get 'users/link_coinbase_account', as: :link_coinbase_account
  get 'users/confirm_coinbase_account'
  get 'users/unlink_coinbase_account', as: :unlink_coinbase_account
  get 'users/access_qrcode', as: :access_qrcode
  get 'users/revoke_access_code', as: :revoke_access_code

  get 'sessions/destroy', as: :sign_out
  match 'sessions/authenticate', via: [:get, :post]
  get 'sessions/fail'
  get 'sessions/oauth', as: :oauth

  match '/dashboard', to: 'dashboard#dashboard', via: :get, as: :dashboard
  get 'dashboard/account_summary'
  get 'dashboard/transfer'
  get 'dashboard/buy_sell_bitcoin'
  get 'transfers/get_price'
  post 'transfers/create'
  get 'dashboard/access_qrcode_details'
  get 'dashboard/bitstation_feed'
  get 'dashboard/view_public_addresses'

  root :to => 'static_pages#homepage'

  match '/about', to: 'static_pages#about', via: :get, as: :about
  match '/beta', to: 'static_pages#beta', via: :get, as: :beta
  match '/security', to: 'static_pages#security', via: :get, as: :security
  match '/faq', to: 'static_pages#faq', via: :get, as: :faq
  match '/team', to: 'static_pages#team', via: :get, as: :team
  match '/privacy', to: 'static_pages#privacy', via: :get, as: :privacy

  resources :transactions, only: [:create, :index, :show] do
    resources :comments, only: [:index, :new, :create, :destroy] do
    end

    member do
      post 'annotate'
      get 'show_external'
    end
  end

  resources :transfers, only: [:create] do
  end

  resources :money_requests, path: 'requests', only: [:show, :index, :create] do
    member do
      post 'pay'
      post 'deny'
      post 'resend'
      post 'cancel'
    end
  end

  resources :contacts, only: [:create, :index, :show, :new, :destroy, :update] do
    collection do
      post 'import', as: :import
    end
  end

  resources :activities, only: [:index] do
  end
end

app/models/money_request.rb
class MoneyRequest < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :requestee, class_name: 'User'

  has_one :associated_transaction, class_name: 'Transaction'

  enum status: [:pending, :paid, :denied, :cancelled]

  include ApplicationHelper

  def to_display_data(current_user)
    {
      time: created_at,
      display_time: created_at.strftime('%b %d'),
      amount: friendly_amount(amount, 'BTC'),
      direction: sender == current_user ? :to : :from,
      money_direction: requestee == current_user ? :to : :from,
      pending: pending?,
      success: paid? ? 'paid' : nil,
      failure: denied? || cancelled? ?
        (denied? ? 'denied' : 'cancelled') :
        nil,
      target: (sender == current_user ? requestee : sender).name,
      target_type: :bitstation,
      load: Rails.application.routes.url_helpers.money_request_path(self)
    }
  end
end

app/controllers/money_requests_controller.rb
class MoneyRequestsController < ApplicationController
  before_filter :ensure_signed_in, only: [:show, :pay, :deny]
  before_filter :ensure_signed_in_without_redirect, only: [:index, :create]
  before_filter :ensure_coinbase_account_linked, only: [:pay, :create]

  include ApplicationHelper

  MONEY_REQUEST_HISTORY_ENTRIES_PER_PAGE = 11

  CURRENCIES = ["USD", "BTC"]

  MINIMUM_TRANSACTION_AMOUNT = {
    "BTC" => 0.001,
    "USD" => 0.5
  }

  def create
    requestee = User.find_by(kerberos: params[:kerberos])
    amount = params[:amount_btc].to_f rescue nil
    currency = 'BTC'
    message = params[:message]

    error = nil
    success = nil

    begin
      (error = 'Invalid currency. ' and raise) unless CURRENCIES.include?(currency)
      (error = 'The designated requestee hasn\'t joined BitStation yet. ' and raise) if requestee.nil?
      (error = 'The designated requestee hasn\'t linked a Coinbase account yet. ' and raise) if requestee.coinbase_account.nil?
      (error = 'Why requesting money from yourself...? ' and raise) if requestee == current_user
      (error = "Invalid request amount. The minimum transaction amount is #{MINIMUM_TRANSACTION_AMOUNT[currency]} #{currency}." and raise) if (amount.nil? || amount < MINIMUM_TRANSACTION_AMOUNT[currency])
    rescue
    end

    unless error
      exchange_rate = current_coinbase_client.spot_price(currency).to_d
      amount /= exchange_rate unless currency == 'BTC'
      dollar_amount = amount * exchange_rate

      # FIXME more specific rescue here
      begin
        mr = MoneyRequest.create!({
          sender: current_user,
          requestee: requestee,
          amount: amount,
          dollar_amount: dollar_amount,
          message: message
        })

        mr.pending!

        TransactionMailer.request_money(current_user, requestee, amount, dollar_amount, message, dashboard_url({
          popup: money_request_path(mr)
        })).deliver

        success = "You successfully sent the money request to #{requestee.name} at #{requestee.coinbase_account.email}. "
      rescue
        error = 'Failed to send the request. '
      end
    end

    @error = error
    @success = success

    respond_to do |format|
      format.js {}
      format.html { redirect_to dashboard_url, flash: {success: success, error: error}.delete_if { |k, v| v.nil? } }
    end
  end

  def show
    @request = (MoneyRequest.find(params[:id].to_i) rescue nil)
    @should_show = (@request.sender == current_user || @request.requestee == current_user)
    @from = @request.sender == current_user ? 'You' : @request.sender.name
    @to = @request.requestee == current_user ? 'you' : @request.requestee.name

    render layout: false
  end

  def pay
    request = (MoneyRequest.find(params[:id].to_i) rescue nil)

    error = nil

    begin
      (error = 'Invalid request to pay. ' and raise) if request.nil?
      (error = 'Request already cancelled. ' and raise) if request.cancelled?
      (error = 'Request already paid or denied. ' and raise) unless request.pending?
      (error = 'Insufficient balance. ' and raise) if request.amount > current_coinbase_client.balance.to_d
    rescue
    end

    if error
      redirect_to dashboard_url, flash: {error: error}
    else
      pt = Transaction.create!({sender: current_user, recipient: request.sender, amount: request.amount, money_request: request})
      redirect_to @oauth_client.auth_code.authorize_url(redirect_uri: coinbase_callback_uri + '?pending_action=transact&pending_action_id=' + pt.id.to_s) + '&scope=send+user'
    end
  end

  def deny
    request = (MoneyRequest.find(params[:id].to_i) rescue nil)

    error = nil

    begin
      (error = 'Invalid request to pay. ' and raise) if request.nil?
      (error = 'Request already cancelled. ' and raise) if request.cancelled?
      (error = 'Request already paid or denied. ' and raise) unless request.pending?
    rescue
    end

    success = "You have successfully denied #{request.sender.name}'s money request. " unless error
    request.denied! unless error

    @error = error
    @success = success

    respond_to do |format|
      format.js {}

      format.html do
        if error
          redirect_to dashboard_url, flash: {error: error}
        else
          redirect_to dashboard_url, flash: {success: success}
        end
      end
    end
  end

  def cancel
    request = (MoneyRequest.find(params[:id].to_i) rescue nil)

    error = nil

    begin
      (error = 'Invalid request to cancel. ' and raise) if request.nil?
      (error = 'Request already cancelled. ' and raise) if request.cancelled?
    rescue
    end

    success = "You have successfully cancelled #{request.sender.name}'s money request. " unless error
    request.cancelled! unless error

    @error = error
    @success = success

    respond_to do |format|
      format.js {}

      format.html do
        if error
          redirect_to dashboard_url, flash: {error: error}
        else
          redirect_to dashboard_url, flash: {success: success}
        end
      end
    end
  end

  def index
    page = [params[:page].to_i, 1].max

    rs = current_user.outgoing_money_requests.to_a + current_user.incoming_money_requests.to_a

    @display = rs.map { |r| r.to_display_data(current_user) }.sort_by { |r| r[:time] }.reverse.drop((page - 1) * MONEY_REQUEST_HISTORY_ENTRIES_PER_PAGE).first(MONEY_REQUEST_HISTORY_ENTRIES_PER_PAGE)

    respond_to do |format|
      format.js do
        @rendered_html = render_to_string(formats: [:html]).lines.join('').html_safe
        # raise @rendered_html.lines.count.to_s
        render formats: [:js]
      end

      format.html do
        render layout: false
      end
    end
  end

  def resend
    request = (MoneyRequest.find(params[:id].to_i) rescue nil)

    begin
      (@error = 'No such request. ' and raise) if request.nil?
      (@error = 'Request already responded to. ' and raise) unless request.pending?

      begin
        TransactionMailer.request_money(
          request.sender,
          request.requestee,
          request.amount,
          request.dollar_amount,
          request.message,
          dashboard_url({
            popup: money_request_path(request)
          }),
          true
        ).deliver

        @success = "You have successfully resent the request to #{request.requestee.name}. "
      rescue
        @error = 'Resending request email failed. '
      end
    rescue
    end

    respond_to do |format|
      format.js {}

      format.html do
        if @error
          redirect_to dashboard_url, flash: {error: @error}
        else
          redirect_to dashboard_url, flash: {success: @success}
        end
      end
    end
  end
end

app/helpers/money_requests_helper.rb
module MoneyRequestsHelper
end

app/views/money_requests/cancel.js.erb
window.trigger_popup_alert("<%= j @success || @error %>", "<%= @success ? 'success': 'error' %>");
$('#money_requests_history_button').click();

app/views/money_requests/create.js.erb
window.trigger_popup_alert("<%= j @success || @error %>", "<%= @success ? 'success': 'error' %>");
$('#money_requests_history_button').click();

app/views/money_requests/deny.js.erb
window.trigger_popup_alert("<%= j @success || @error %>", "<%= @success ? 'success': 'error' %>");
$('#money_requests_history_button').click();

app/views/money_requests/index.html.erb
<%= render 'account_activity_history', id: 'money-requests-history-table', data: @display, activity: 'money request', prev_page: @prev_page, next_page: @next_page %>

<!-- FIXME this too is ugly -->
<script>
  window.setup_paging_links('#money-requests-history-table');
</script>

app/views/money_requests/index.js.erb
$('#account_activity_history_module').html('<%= j @rendered_html %>')

app/views/money_requests/resend.js.erb
window.trigger_popup_alert("<%= j @success || @error %>", "<%= @success ? 'success': 'error' %>");

app/views/money_requests/show.html.erb
<% if @request %>
  <% if @should_show %>
    <div class="panel-body">
      <h4>Money Request Details</h4>
      <p>Sent on <%= @request.created_at.strftime('%b %d, %Y at %I:%M %p') %></p>

      <%= transaction_description_labels(@from, :request, @to, @request.amount) %>
    </div>

    <% if @request.message && !@request.message.strip.empty? %>
      <hr>
      <div class="panel-body">
        <p>Here is the message attached: </p>
        <p><%= @request.message %></p>
      </div>
    <% end %>

    <% if @to == 'you' && @request.pending? %>
      <hr>
      <div class="panel-body">
        <%= link_to 'Pay', pay_money_request_path(@request), method: :post, class: 'btn btn-primary' %>
        <%= link_to 'Deny', deny_money_request_path(@request), method: :post, class: 'btn btn-primary', remote: true, data: {confirm: 'Do you really want to deny this money request? '} %>
      </div>
    <% end %>

    <% if @from == 'You' && @request.pending? %>
      <hr>
      <div class="panel-body">
        <%= link_to 'Resend', resend_money_request_path(@request), method: :post, class: 'btn btn-primary', remote: true %>
        <%= link_to 'Cancel', cancel_money_request_path(@request), method: :post, class: 'btn btn-primary', remote: true, data: {confirm: 'Do you really want to cancel this money request? '} %>
      </div>
    <% end %>

    <hr>

    <div class="panel-body">
      <% if @request.paid? %>
        <p>The request has already been paid on <%= @request.updated_at.strftime('%b %d, %Y at %I:%M %p') %>. </p>
      <% end %>

      <% if @request.denied? %>
        <p>The request has been denied by the requestee on <%= @request.updated_at.strftime('%b %d, %Y at %I:%M %p') %>. </p>
      <% end %>

      <% if @request.pending? %>
        <p>The requestee hasn't responded to the request yet. </p>
      <% end %>

      <% if @request.cancelled? %>
        <p>The request has been cancelled by the sender on <%= @request.updated_at.strftime('%b %d, %Y at %I:%M %p') %>. </p>
      <% end %>
    </div>
  <% else %>
    <div class="panel-body">You can only view requests that are either sent by you or to you. </div>
  <% end %>
<% else %>
  <p>No such request. </p>
<% end %>