config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/new'

  get 'comments/create'

  get 'transfers/index'

  get 'search_suggestions/user/:query', to: 'search_suggestions#user'

  get 'users/require_coinbase_account', as: :require_coinbase_account
  get 'users/link_coinbase_account', as: :link_coinbase_account
  get 'users/confirm_coinbase_account'
  get 'users/unlink_coinbase_account', as: :unlink_coinbase_account
  get 'users/access_qrcode', as: :access_qrcode
  get 'users/revoke_access_code', as: :revoke_access_code

  get 'sessions/destroy', as: :sign_out
  match 'sessions/authenticate', via: [:get, :post]
  get 'sessions/fail'
  get 'sessions/oauth', as: :oauth

  match '/dashboard', to: 'dashboard#dashboard', via: :get, as: :dashboard
  get 'dashboard/account_summary'
  get 'dashboard/transfer'
  get 'dashboard/buy_sell_bitcoin'
  get 'transfers/get_price'
  post 'transfers/create'
  get 'dashboard/access_qrcode_details'
  get 'dashboard/bitstation_feed'
  get 'dashboard/view_public_addresses'

  root :to => 'static_pages#homepage'

  match '/about', to: 'static_pages#about', via: :get, as: :about
  match '/beta', to: 'static_pages#beta', via: :get, as: :beta
  match '/security', to: 'static_pages#security', via: :get, as: :security
  match '/faq', to: 'static_pages#faq', via: :get, as: :faq
  match '/team', to: 'static_pages#team', via: :get, as: :team
  match '/privacy', to: 'static_pages#privacy', via: :get, as: :privacy

  resources :transactions, only: [:create, :index, :show] do
    resources :comments, only: [:index, :new, :create, :destroy] do
    end

    member do
      post 'annotate'
      get 'show_external'
    end
  end

  resources :transfers, only: [:create] do
  end

  resources :money_requests, path: 'requests', only: [:show, :index, :create] do
    member do
      post 'pay'
      post 'deny'
      post 'resend'
      post 'cancel'
    end
  end

  resources :contacts, only: [:create, :index, :show, :new, :destroy, :update] do
    collection do
      post 'import', as: :import
    end
  end

  resources :activities, only: [:index] do
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if Rails.env.development? %>
      [Dev]
    <% end %>
    BitStation
    <% if @subtitle %>
      <%= " - #{@subtitle}" %>
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="<%= "#{params[:controller]}-#{params[:action]}" %>" class="<%= "#{params[:controller]}-action" %>">
  <div class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'BitStation', root_path, class: 'navbar-brand text-hide' %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-right">
          <li><p class="navbar-text">Welcome, <%= current_user_name %> <%= signed_in_with_access_code? ? '(*)' : ''%></li>
            <% if signed_in? %>
              <%= link_to 'Sign out', sign_out_path, class: "btn btn-primary btn-sm pull-right" if signed_in? %>
            <% elsif !@auth_link.nil? %>
              <% if Rails.env.development? %>
                <%= link_to 'Nelly\'s Backdoor', @nelly_auth_link, class: 'btn btn-primary btn-sm pull-right' %>
              <% end %>
              <%= link_to 'MIT Certificate Login', @auth_link, class: 'btn btn-primary btn-sm pull-right' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div id="wrapper-main" class="<% if params[:controller] == "dashboard" %>
                <%= "container" %>
              <% else %>
                <%= "container-fluid" %>
              <% end %>">
    <div class="row"><% flash.each do |key, value| %>
      <% next unless ['success', 'warning', 'info', 'error'].include?(key.to_s) %>
      <div class="alert alert-<%= key.to_s == 'error' ? 'danger' : key.to_s %> <%= key.to_s == 'success' ? '' : 'alert-dismissible' %>" role="alert">
        <% if key.to_s != 'success' %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <% end %>
        <%= value %>
      </div>
    <% end %>
    <% if @flash %>
      <% @flash.each do |key, value| %>
        <% next unless ['success', 'warning', 'info', 'error'].include?(key.to_s) %>
        <div class="alert alert-<%= key.to_s == 'error' ? 'danger' : key.to_s %> <%= key.to_s == 'success' ? '' : 'alert-dismissible' %>" role="alert">
          <% if key.to_s != 'success' %>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <% end %>
          <%= value %>
        </div>
      <% end%>
    <% end %>
    </div>
    <%= yield %>
  </div>

  <%= javascript_include_tag "application" %>

  <!-- Facebook SDK -->
  <div id="fb-root"></div>

  <script>
    if (typeof (FB) != 'undefined') {
      FB.init({ status: true, cookie: true, xfbml: true });
    } else {
      $.getScript("https://connect.facebook.net/en_US/all.js#xfbml=1", function () {
        FB.init({ status: true, cookie: true, xfbml: true });
      });
    }
  </script>

  <!-- FOOTER -->
  <footer class="container">
    <div class="">
      <p class="pull-right"><a href="#">Back to top</a></p>
      <p>&copy; 2014 BitStation. &middot;
        <%= link_to 'About', about_path %> &middot;
        <%= link_to 'Security', security_path %> &middot;
        <%= link_to 'FAQ', faq_path %> &middot;
        <%= link_to 'Team', team_path %> &middot;
        <%= link_to 'Privacy', privacy_path %> &middot;
        <a href="mailto:bitstation@mit.edu" target="_top">Contact</a>
      </p>
    </div>
  </footer>

</body>
</html>

app/views/layouts/basic_mailer.html.erb
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="-webkit-text-size-adjust: none;margin: 0;padding: 0;background: #eeee;width: 100%;" bgcolor="#eee">
  <center>
    <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 0;padding: 0;height: 100%;width: 100%; background: #eeeeee;">
      <tr>
        <td align="center" valign="top">
          <table border="0" cellpadding="40" cellspacing="0" width="480" id="contentWrapper">
            <tr>
              <td>
                <!-- // Begin Template Preheader -->
                <!-- // End Template Preheader -->
                <table border="0" cellpadding="0" cellspacing="0" width="480" id="templateContainer" style="background-color: #FFFFFF;">
                  <tr>
                    <td>
                      <table border="0" cellpadding="0" cellspacing="0" width="480">
                        <tr>
                          <td align="center" valign="top">
                            <th style="text-align: center; padding-top:5px; padding-bottom: 4px; background-color: #428bca; color: #fff; font-family: 'Helvetica Neue';">Request Details</th>
                            <!-- // Begin Template Body -->
                            <table border="0" cellpadding="24" cellspacing="0" height="50" style="border-bottom:1px solid #eee; padding:0 16px" width="480">
                            <tr>
                              <td valign="top" style="background-color: #FFFFFF;">
                                <a href="/accounts/last"><img alt="Coinbase" src="http://bit.ljh.me/assets/brand-8429edb36880ead25ac79b457d17eadc.png" width="150" /></a>
                              </td>
                              <td style="text-align: right;"></td>
                            </tr>
                          </table>
                          <!-- // End Template Body -->
                        </td>
                      </tr>
                      <tr>
                        <td align="center" valign="top">
                          <!-- // Begin Template Body -->
                          <%= yield %>
                          <!-- // End Template Body -->
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <!-- // Begin Template Footer -->
            <table border="0" cellpadding="5" cellspacing="0" width="520" id="templateFooterWrap">
              <tr>
                <td align="center" valign="top">
                  <table border="0" cellpadding="0" cellspacing="0" width="510" id="templateFooter">
                    <tr>
                      <td valign="top">
                        <!-- // Begin Module: Standard Footer -->
                        <table border="0" cellpadding="0" cellspacing="0" width="100%">
                          <tr>
                            <td valign="middle" width="520">
                              <div style="color: #b3b3b3;font-family: Helvetica, Arial;font-size: 11px;line-height: 125%;text-align: center;">
                                <br>&copy; BitStation 2014</div>
                                <br>
                              </td>
                            </tr>
                          </table>
                          <!-- // End Module: Standard Footer -->
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
              <br>
              <!-- // End Template Footer -->
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</center>
</body>

</html>